services:
  backend:
    build:
      context: ..                 # <- one level up from docker/, i.e., backend/
      dockerfile: docker/Dockerfile
    container_name: studymate-backend
    ports:
      - "5000:5000"
    env_file:
      - ../.env                   # ../ resolves to backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: studymate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
